### PR TITLE
Fixed #85, styling bug on selecting number

### LINKED ISSUE #85: Slider Scale Numbers Data ID Problem
The `data-id` is being set to the value of the `slider-scale-number` this is ok if the slider is 1-10 but when values are changed, as in a date range ie 1920-1930 the `slider-handle` and `slider-bar` is going way off the component with the `left` property being set. See screenshots from more detail:

image

image

### PR DESCRIPTION
**Pull request by brian-learningpool**
This was due to a few issues with  onNumberSelected().

I've also corrected the properties.json for the authoring tool.

### CODE REVIEW

File: js/adapt-contrib-slider.js [hunk 1]
```diff
@@ -256,11 +256,16 @@ define(function(require) {
...
+              return;
+            }
+
+            var index = this.getIndexFromValue(parseInt($(event.currentTarget).attr('data-id')));
+            var $scaler = this.$('.slider-scaler');
             this.selectItem(index);
-            this.animateToPosition(this.mapIndexToPixels(index));
-            this.setAltText(index + 1);
+            this.animateToPosition(this.mapIndexToPixels(index, $scaler));
+            this.setAltText(index);
```
Comment (moloko) [inline js/adapt-contrib-slider.js]: this need to be `(index + 1)` as before - otherwise the `aria-valuenow` label gets set to 1 less than the selected index (i.e. if I click on the number 3 then `aria-valuenow="2"`)

Comment (moloko) [inline js/adapt-contrib-slider.js]: yes, it's definitely getting it wrong because `getIndexFromValue` is returned a 0-based index of the markers... so it's even more inaccurate if you change the range to be something like 10 - 20 - clicking on 15 will give you an `aria-valuenow` label of 6!
A better way would be to store the value first, so something like this:
```
var itemValue = parseInt($(event.currentTarget).attr('data-id'));
var itemIndex = this.getIndexFromValue(itemValue);
```
Then do this:
```
this.setAltText(itemValue);
```
This also needs changing in `onDragReleased`

Clicking on the slider bar also results in an incorrect `aria-valuenow` value - but I can't quite figure out how to fix it (it's in `onSliderSelected`)

File: properties.schema [hunk 2]
```diff
@@ -101,31 +101,31 @@
       "help": "What number the scale should end on"
     },
     "_correctAnswer": {
-      "type":"number",
-      "default": 1,
+      "type": "string",
```
Comment (moloko) [inline properties.schema]: presumably this will allow the user to enter a non-numerical value?

Comment (brian-learningpool) [inline properties.schema]: Yes, it will, but it's per the README.  The problem is that the component appears to have been designed in a way such that if `_correctAnswer` is empty then the range kicks in.  We could probably parse it in the component itself to mitigate against non-number strings in the JSON.

**Comment by ciaranlp** [comment]
great work happy days 

+1

**Comment by moloko** [comment]
+1

**Comment by lc-thomasberger** [comment]
+1

**Comment by hrajotia** [comment]
+1

**Comment by taylortom** [comment]
+1
