### PR TITLE
Fix: aria-valuetext attribute added to the slider to read out scaleStepPrefix/scaleStepSuffix (fixes #211)

### LINKED ISSUE #211: Scale step prefix & suffix are not read out by the screen reader
### Subject of the issue/enhancement/features
The scaleStepPrefix & scaleStepSuffix are currently not read out by the screenreader, 

### Your environment

- FW v5.40.3
- Latest Firefox
- Windows, NVDA

### Steps to reproduce
Create a course with a slider, set the scaleStepPrefix/scaleStepSuffix and navigate through the course using a screenreader/keyboard

### Expected behaviour
The scaleStepPrefix/scaleStepSuffix should be read out to ensure screenreader users don't miss any information

### Actual behaviour
They are not read out

### PR DESCRIPTION
**Pull request by joe-allen-89**
[//]: # (Please title your PR according to eslint commit conventions)
[//]: # (See https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-eslint#eslint-convention for details)

[//]: # (Link the PR to the original issue)
#211 

[//]: # (Delete Fix, Update, New and/or Breaking sections as appropriate)
### Fix
* aria-valuetext attribute added to the slider to read out scaleStepPrefix/scaleStepSuffix(fixes #211)

### CODE REVIEW

File: templates/slider.jsx [hunk 1]
```diff
@@ -177,6 +177,7 @@ export default function Slider (props) {
           <input className='slider__item-input js-slider-item-input'
             type='range'
             aria-label={ariaScaleName}
+            aria-valuetext={(scaleStepPrefix || scaleStepSuffix) && `${scaleStepPrefix} ${selectedValue} ${scaleStepSuffix}`}
```
Comment (oliverfoster) [inline templates/slider.jsx:180]: It looks like it won't read anything if there is no prefix or suffix.

Comment (joe-allen-89) [reply templates/slider.jsx:180]: If there is no prefix or suffix the value of the input is read out, it doesn't override the value but gives a text alternative from my understanding. 

https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-valuetext

Comment (oliverfoster) [reply templates/slider.jsx:180]: > If there is no prefix or suffix

What about if they are both null string, as they would be in the aat?

I think it should be 
```
aria-valuetext={(scaleStepPrefix || scaleStepSuffix) ? `${scaleStepPrefix} ${selectedValue} ${scaleStepSuffix}` : null}
```

Comment (joe-allen-89) [reply templates/slider.jsx:180]: Apologies @oliverfoster, bad grammar on my part, if there isn't a prefix AND there isn't a suffix, the aria-valueText string will be blank and the screen reader defaults to reading out the value of the input which seems to work as expected but will test your above solution.

Comment (joe-allen-89) [reply templates/slider.jsx:180]: Whilst they both work as expected, you're absolutely right that adding null to the conditional removes the attribute from the element rather than just leaves it with an empty string, agree this is the best way forward.

**Review by oliverfoster — APPROVED** [review]

**Review by cahirodoherty-learningpool — APPROVED** [review]
👀

**Review by kirsty-hames — APPROVED** [review]
Works as expected thanks. Tested with VoiceOver on Mac 👍
